### ISSUE TITLE
When all required spikes are done, document the chosen design

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#10]
We want to diagram and explanation of:

 * The architecture
 * The flow of data (where it's at rest etc.)
     * Permissions (who can do what?)

## Documentation

 * https://www.notion.so/Proposed-solution-for-internal-global-reports-6b48e251861842ca8b2c7a6ea76c15fd

**Comment by darylhedley** [comment]
https://www.notion.so/Proposed-solution-for-internal-global-reports-6b48e251861842ca8b2c7a6ea76c15fd

**Comment by jon-betts** [comment]
Everyone is mad happy with this
