### ISSUE TITLE
Teachers In Organization (Fast / SQL) report is not working anymore

### ISSUE THREAD

**Issue by darylhedley** [hypothesis/report#179]
Looking at this page we had: 
https://report.hypothes.is/dashboard/6-organization-focus?organization_id=us.lms.org.hvz-D3-6S5aQMldCoLNLZQ&timescale=semester&role=user&group_type=course
Which returned teachers in an organization but this has recently stopped working.

Digging into groups/courses also has a broken report:
https://report.hypothes.is/dashboard/17-group-focus?group_id=us-25514222

Looks like something has moved and isn't working as expected.

Direct links to example reports:

 * https://report.hypothes.is/question/118-teachers-in-organization-fast-sql?public_id=us.lms.org.TARKQ36QQAGEfIowmGOuGQ
 * https://report.hypothes.is/question/117-teachers-in-group-fast-sql?group_id=us-25514222

## Tickets

 * [x] https://github.com/hypothesis/report/pull/178
 * [x] https://github.com/hypothesis/report/pull/181

**Comment by jon-betts** [comment]
Done!
