### ISSUE TITLE
Top Active Organizations This Semester report is returning two organizations and should return one

### ISSUE THREAD

**Issue by darylhedley** [hypothesis/report#180]
Looking at this report: https://report.hypothes.is/question/57-top-active-organizations-this-semester
You can see two organizations are returned in the list and looks like it's viewing two semesters rather than just the current semester.

This view should only ever show one set of data per organization and be the current semester.

**Comment by jon-betts** [comment]
This should be fixed now. The default join in Metabase is a "LEFT OUTER". So we were joining onto the latest period table, but not filtering out rows that didn't match.
