### ISSUE TITLE
Flag contacts in Hubspot as LMS users

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#216]
Partially achieves:

 * https://github.com/hypothesis/report/issues/212

Tasks:

 * [x] https://github.com/hypothesis/devdata/pull/86
 * [x] https://github.com/hypothesis/report/pull/218
 * [x] Get a field to upload our details to in Hubspot
 * [x] Update our Live key to include the scope for reading and updating contacts
 * [x] https://github.com/hypothesis/report/pull/217
 * [x] https://github.com/hypothesis/report/pull/220
 * [x] https://github.com/hypothesis/report/pull/219
 * [x] https://github.com/hypothesis/report/pull/222
 * [x] https://github.com/hypothesis/report/pull/223

Follow-up

 * [x] Update our QA key to include the scope for reading and updating contacts
 * [x] Can we / should we filter the records we update by "Marketing Contact Status" or any other field?
    * Nope. That's for HS to work on
 * [x] Investgate the new bulk exports end-point to see if it's faster: https://developers.hubspot.com/docs/api/crm/exports
     * It's pretty slow. It took 29 minutes to generate when I tried
     * We're curious to see if we can filter these results
     * Turns out the search way of doing it is probably the way. Should be about 2m

## Why

In order to contact people who aren't a contact in order to try and get sales.

## How

We should match users by their email addresses in Hubspot. This will involve:

 * Pulling contact records from Hubspot
 * Filtering them by those which have email addresses
 * Match those who match up with a user in LMS
 * Send back a field which says they are

## What we need

 * A field to store the state in Hubspot
 * An idea of what to put in that field

## Risks

 * Can we update contact records?
 * How long does it take to pull all the contact records?

**Comment by nairiboo** [comment]
Per Slack conversation:

Need to confirm we are happy with below:

- The period is weekly
- The field is called LMS Role and takes Teacher , Student or none
- We don't need to worry about teachers stopping being teachers

The current risks are:

- We don't know how long it will take to run when we do the full set

@nairiboo confirming

**Comment by nairiboo** [comment]
@jon-betts Joe has responded that those defaults make sense to him so we're good to go.

Question; can you confirm: we will not import student record data, correct? We don’t need it and would rather keep CRM clean.

**Comment by nairiboo** [comment]
Following deploying the report;

The field isn't visible on the contact default view yet, as the layout needs to be updated, but if you:

- Click the "Actions" menu on a contact
- Then pick "View all properties"
- Then scroll to the very bottom and open "Report"

You should see the new value. It will be blank for nearly all contacts. We have ~11k of the 512k contacts marked as teachers. [Example here](https://app.hubspot.com/contacts/6291320/record/0-1/80106151).

**Question to answer**
- Does the field need to be visible on the contacts main page or are we using the information purely for running processes (i.e sending emails)?


There are a couple of tidy up tasks if we are happy with this:

- Make the comparison case insensitive
- Set an automatic job to run and do this weekly
