### ISSUE TITLE
Course health metrics

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#235]
For:

 * https://github.com/hypothesis/report/issues/205

[Link to example dashboard](https://report.hypothes.is/dashboard/17-group-focus?group_id=us-24333504)

## Other stuff

* [x] Can click through user name
* [x] Remove activity table? Yes
* [x] Slim down activity graph to just launches

### Instructor annotations

> - no. of annotations by instructor
>   - no. of shared
>   - no. of replies

Does "by instructor" here mean total number of annotations made by teachers, or does this mean number of annotations for by each teacher?

Shares and replies are a bit weird as the only two metrics, as they are one example of two different categories:

 * Shared / Private
 * Annotation / Reply / Page-note / Highlight

Reports:

 * [x] Annotations by role over time

Tasks:

 * [x] https://github.com/hypothesis/h/pull/8023
 * [x] https://github.com/hypothesis/lms/pull/5516
 * [x] https://github.com/hypothesis/report/pull/239
 * [x] https://github.com/hypothesis/lms/pull/5518
 * [x] Create Report
 * [ ] Try and remove duplicated tables
    * [x] https://github.com/hypothesis/report/pull/242
    * [x] https://github.com/hypothesis/lms/pull/5517
    * [x] https://github.com/hypothesis/h/pull/8026
    * [x] https://github.com/hypothesis/lms/pull/5536
    * [x] https://github.com/hypothesis/report/pull/252
    * [x] Stop using `organization_annotation_type` view
    * [x] https://github.com/hypothesis/report/pull/253
    * [x] https://github.com/hypothesis/lms/pull/5539
    * [x] https://github.com/hypothesis/report/pull/254
    * [x] https://github.com/hypothesis/report/pull/256
### Students per instructor annotations

> - no. of annotations per student per instructor (in associated courses)
>   - no. of shared
>   - no. of replies

I'm not sure what "per student per instructor" means. Students are not specifically associated with teachers. If a teacher is in a group and a student is in a group that's all the relationship we have.

We don't have "student" as a category, we have "user" which includes teachers too.

Are we talking about replies to and from different users? This would be tricky.

Similar weirdness around shared and replies being the only things.

Reports:

 * Sorted by the Annotations by role over time graph above

### Annotation sub-types

> - Breakdown of annotation type

Reports:

 * [x] Weekly breakdown of annotation sub-type
 * [x] Weekly breakdown of shared vs. private (??? This sort of addresses the above shared / replies not not really)

### Assignments

> - Breakdown by assignment 

Breakdown of what? Annotations. So we can't do it.

## Who is the audience of the data?

- Short term: Success
- Long term: Customers (Accessible within the tool e.g. a dashboard)

**Comment by nairiboo** [comment]
>Does "by instructor" here mean total number of annotations made by teachers, or does this mean number of annotations for by each teacher?

>Shares and replies are a bit weird as the only two metrics, as they are one example of two different categories:

>- Shared / Private
>- Annotation / Reply / Page-note / Highlight

I'd say if we're doing some sort of pie charts then total number made by teachers with the breakdown you've listed above. If we're doing a detailed table then each individual teacher so they can dig in further.

---

>We don't have "student" as a category, we have "user" which includes teachers too.

I guess this means we can't really do anything to show the student vs instructor behaviour then? So the requirement is moot?

---

>Breakdown of what?

I think that was meant to be breakdown of annotations per assignment in the course but you'd said it wasn't possible so i think we'll just have to scrap that one.

**Comment by jon-betts** [comment]
> I'd say if we're doing some sort of pie charts then total number made by teachers with the breakdown you've listed above. If we're doing a detailed table then each individual teacher so they can dig in further.

I guess that's the question. What do users want / need?

> I guess this means we can't really do anything to show the student vs instructor behaviour then? So the requirement is moot?

The categories we have are "All users" and "Teachers". So we can say x% of the annotations are by teachers. It's a minor difference but it comes up a lot. The reason for the difference is some students are teachers too, so adding up the number of students and teachers gets you to over 100%.

So the main idea is probably still sound with a slight tweak (depending on what the idea is, I'm not sure).

**Comment by jon-betts** [comment]
I think this is done? We don't really have an acceptance procedure.
