### ISSUE TITLE
Create walking skeleton end-to-end

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#3]
By now we should have:

 * Syncing jobs in H
 * FWD from LMS to H

We are are missing:

 * [x] A project with Metabase as an app
 * [x] Metabase + DB deployed
 * [x] Syncing jobs in LMS (we can copy method?)
 * [ ] FDW from Metabase DB to regional LMS / H read replica
 * [ ] Sync job for Metabase DB
 * [ ] One report report based on the table in Metabase

The report should:

* Show some data that came from H via LMS
* Include data from two regions and allow filtering by region
* It does not need to make any sense at all

### Note!

This ticket is moving ahead of tickets it depends on, because Iain is getting a head start.

**Comment by indigobravo** [comment]
The operational components are now in place to enable this happen. Details have been written up against: [Proposed solution for internal global reports](https://www.notion.so/Proposed-solution-for-internal-global-reports-6b48e251861842ca8b2c7a6ea76c15fd#b7cb30ee798f4b1bb947eb64de19a90e)

**Comment by jon-betts** [comment]
It might not be very flashy yet, but we are moving data through all portions of the system. So I think this is done.
